const SOURCE_TYPE_FILE = "FILE";
const SOURCE_TYPE_API = "API";
const SOURCE_TYPE_DATABASE = "DATABASE";


const INGESTION_SOURCE_TYPES = [
    SOURCE_TYPE_FILE,
    SOURCE_TYPE_API,
    SOURCE_TYPE_DATABASE
]

module.exports = {
    INGESTION_SOURCE_TYPES,
    SOURCE_TYPE_FILE,
    SOURCE_TYPE_API,
    SOURCE_TYPE_DATABASE
}